### ISSUE TITLE
Add comments to DSA code for better understanding

### ISSUE THREAD

**Issue by RishabxBhardwaj** [rupesh-dev30/DSA-in-CPP#1]
Description: We need to add detailed and descriptive comments to the existing DSA code to improve readability and help others understand the logic and flow of the algorithms. Each code block should have inline comments explaining the purpose of the function, variables, and key steps in the algorithm.

Tasks:

Review the existing DSA code.
Add comments explaining the functionality of key sections of the code.
Ensure all variable names, functions, and complex logic are properly explained.
Maintain consistency and clarity in the comments.
Ensure comments follow best practices (e.g., avoid redundant comments, focus on explaining why and how, rather than what).
Additional Information:

Keep the comments concise yet informative.
Use proper terminology related to data structures and algorithms.

**Comment by rupesh-dev30** [comment]
Thanks for pointing this out! Would you be able to take this on? I can assign the task to you if you're available.

**Comment by RishabxBhardwaj** [comment]
plz assign me this
